set -g prefix C-Space
unbind C-b
bind-key C-Space send-prefix

set -g mouse on

# Automatically renumber windows when one is killed.
set -g renumber-windows on

# Set the appropriate title.
set -g set-titles on

# Always use vim keybindings.
set -g mode-keys vi

# Don't add any delay for pressing the escape key.
# Without this, vim becomes *really* annoying to use.
# The default is 500ms. Reduce it substantially.
set -g escape-time 20

set -g default-terminal "screen-256color"
set-option -sa terminal-overrides ",xterm-256color:RGB"

# Convenient config reloading.
unbind r
bind r source-file "$HOME/.tmux.conf"

# Set the appropriate title.
set -g set-titles on

# When opening a new window, use the CWD of the current pane.
unbind c
bind c new-window -c "#{pane_current_path}"

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# Enables `copy-selection` when using mouse dragging.
unbind -T copy-mode-vi MouseDragEnd1Pane

# Nicer way to split panes.
unbind %
unbind '"'
bind -r | split-window -h -c "#{pane_current_path}"
bind -r - split-window -v -c "#{pane_current_path}"

# Maximize or minimize the current pane.
bind -r m resize-pane -Z

# Easy to resize panes.
bind -r k resize-pane -U 4
bind -r j resize-pane -D 4
bind -r h resize-pane -L 4
bind -r l resize-pane -R 4

# Easy to navigate between panes.
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Easy to navigate between windows.
bind -n M-, last-window
bind -n M-0 select-window -t 0
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
