syntax on
set background=dark
colorscheme solarized

" Before saving the buf, remove any trailing whitespace for each line
autocmd BufWritePre * %s/\s\+$//e

" Options
set nonumber
set norelativenumber
set cursorline
set wrap
set textwidth=0
set incsearch
set nohlsearch
set ignorecase
set smartcase
set scrolljump=-50
" set scrolloff=4
set clipboard=unnamed
set mouse=a
set guicursor=""
set fileencoding="utf-8"
set formatoptions=tcqrow
set wildmenu
set showcmd
set backspace=2
set laststatus=0
set hidden
set ruler

" Indent
set noexpandtab
set softtabstop=0
set shiftwidth=8
set tabstop=8
set cindent
set cinoptions=(0,u0,U0

set nobackup
set noswapfile
set undofile
set undodir^=~/dotfiles/.vim/.undo//

" I'll only be using this if I'm on Windows
if has("gui_running")
	set guioptions-=m "Hides the menubar
	set guioptions-=T "Hides the toolbar
	set guioptions-=l "hides the scrollbar
	set guioptions-=L "hides the scrollbar
	set guioptions-=r "hides the scrollbar
	set guioptions-=i "Hides the vim icon
	set guifont=Source\ Code\ Pro\ Regular:h16

	source $HOME\dotfiles\.vim\opt\zoom.vim
	if mapcheck('-') != ''
		unmap -
	endif
	if mapcheck('+') != ''
		unmap +
	endif
	map <C-=> <cmd>ZoomIn<CR>
	map <C-_> <cmd>ZoomOut<CR>
	map <C-0> <cmd>ZoomReset<CR>
endif

" Keymaps
let mapleader=" "
let maplocalleader=" "
noremap <F2> <cmd>source $HOME/dotfiles/.vim/vimrc<CR>

nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>e :bd<CR>
xnoremap <leader>p "_dP

inoremap fj <ESC>
inoremap FJ <ESC>
cnoremap fj <ESC>
cnoremap FJ <ESC>
xnoremap fj <ESC>
xnoremap FJ <ESC>

" Stay in visual mode after indenting
xnoremap > >gv
xnoremap < <gv

" Easy window resize
nnoremap <C-k> 2<C-w>+
nnoremap <C-j> 2<C-w>-
nnoremap <C-h> 2<C-w><
nnoremap <C-l> 2<C-w>>

# Sneak
let g:sneak#label = 1
let g:sneak#use_ic_scs = 1
map s <Plug>Sneak_s
map S <Plug>Sneak_S
map f <Plug>Sneak_f
map F <Plug>Sneak_F

" FZF
set rtp+=/opt/fzf
let g:fzf_vim = {} " Initialize configuration dictionary
let g:fzf_layout = { "window": { "width": 0.9, "height": 0.9 } }
let g:fzf_vim.preview_window = [] " Disable preview
map <leader>f :Files<CR>
map <leader>b :Buffers<CR>
