vim.g.netrw_banner = 0
vim.g.netrw_preview = 1
vim.g.netrw_liststyle = 3
vim.g.netrw_winsize = 30

vim.opt.guicursor = [[a:block-blinkwait700-blinkoff400-blinkon250-Cursor/lCursor]]

vim.opt.laststatus = 0
vim.opt.number = false
vim.opt.relativenumber = false
vim.opt.wrap = true
vim.opt.termguicolors = true
vim.opt.backup = false
vim.opt.fileencoding = "utf-8"
vim.opt.clipboard:append("unnamedplus")
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.opt.ignorecase = true
vim.opt.showmode = true
vim.opt.mouse = "a"
vim.opt.expandtab = false
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.autoindent = true
vim.opt.copyindent = true
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.undofile = true
vim.opt.timeoutlen = 1000
vim.opt.updatetime = 50
vim.opt.writebackup = true
vim.opt.cursorline = true
-- vim.opt.colorcolumn = {"72", "80", "120"}
vim.opt.scrolloff = 999
vim.opt.sidescrolloff = 0
-- vim.opt.scrolljump = -50
